services:
  backend:
    build: ./backend
    networks:
      - portfolio-net

  frontend:
    build: ./frontend/portfolio
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-net

networks:
  portfolio-net:
